local SC = SoloCollections
local UI = SC.UI

SC.EzWardrobe = SC.EzWardrobe or {}
local Assets = SC.EzWardrobe.Assets or {}
SC.EzWardrobe.Assets = Assets

-- This adapter describes the user-authorized local media projection only. The
-- projection is generated by SoloClientSuite and deliberately remains outside
-- the public SoloCollections source/release boundary.
Assets.PROVENANCE = {
    sourceName = "ezCollections",
    sourceVersion = "2.2",
    sourceAuthor = "ZEUStiger",
    sourceTreeHash = "218c65a59b42d810935963013cdf6b729cd7d1d69dc67a52a70632b89911c7f6",
    assetTreeHash = "4673b2c8631c5f28050b9eecde7dad4a6bb33dc6a2ed5f0630a64a17945dbf53",
    publicReleaseState = "LOCAL_INTEGRATION_ONLY",
}

Assets.SOUNDS = {
    open = "UI_EtherealWindow_Open.wav",
    close = "UI_EtherealWindow_Close.wav",
    apply = "UI_Transmogrify_Apply.wav",
}

function Assets:GetStatus()
    return SC.EzCollectionsUI and SC.EzCollectionsUI.GetStatus
        and SC.EzCollectionsUI.GetStatus() or { available = false, reason = "asset-addon-missing" }
end
function Assets:Path(relative)
    if not SC.EzCollectionsUI or not SC.EzCollectionsUI.Path then return nil end
    return SC.EzCollectionsUI.Path(relative)
end

function Assets:MediaPath(group, name, fallback)
    if UI.EzCollections and UI.EzCollections.MediaPath then
        return UI.EzCollections:MediaPath(group, name, fallback)
    end
    return fallback
end

function Assets:Play(key)
    local filename = self.SOUNDS[key]
    if not filename or not PlaySoundFile then return end
    local path = self:Path("Sounds\\" .. filename)
    if path then pcall(PlaySoundFile, path) end
end

function Assets:ApplyItemsPanel(panel)
    local inset = UI.EzCollections:ApplyInset(panel)
    UI.EzCollections:AddShadowOverlay(panel)
    SC.WardrobeUI.Layout:StylePanel(panel, inset.background)
    panel:SetScript("OnShow", function() Assets:Play("open") end)
    panel:SetScript("OnHide", function() Assets:Play("close") end)
    return inset
end

function Assets:ApplyWardrobeControls(frame)
    if not frame or frame.scEzWardrobeControlsStyled then return end
    frame.scEzWardrobeControlsStyled = true
    if frame.scSearchBox then UI.EzCollections:SkinSearchBox(frame.scSearchBox) end
    if frame.scFilterButton then UI.EzCollections:SkinSilverMenuButton(frame.scFilterButton) end
    if frame.scWardrobeTabs then
        frame.scWardrobeTabs:SetWidth(150)
        frame.scWardrobeTabs:SetHeight(24)
    end
end
