[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$AddonRoot,
    [Parameter(Mandatory)][string]$ModuleRoot,
    [Parameter(Mandatory)][string]$CoreRoot,
    [Parameter(Mandatory)][string]$CoreBuildRoot,
    [string]$WorldserverPath = '',
    [ValidateSet('Release','RelWithDebInfo','Debug')][string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3.0
. (Join-Path $PSScriptRoot 'RoundTwoRelease.Common.ps1')

$addon = Resolve-RoundTwoPath $AddonRoot
$module = Resolve-RoundTwoPath $ModuleRoot
$core = Resolve-RoundTwoPath $CoreRoot
$build = Resolve-RoundTwoPath $CoreBuildRoot -AllowMissing
New-Item -ItemType Directory -Force -Path $build | Out-Null
$manifestPath = Join-Path $addon 'catalog\generated\catalog-manifest.json'
$manifest = Read-RoundTwoJson $manifestPath
$values = [ordered]@{
    addonCommit = Get-RoundTwoCommit $addon
    moduleCommit = Get-RoundTwoCommit $module
    coreCommit = Get-RoundTwoCommit $core
    metadataVersion = [string]$manifest.metadataVersion
    assetPackVersion = [string]$manifest.assetPackVersion
    mappingHash = [string]$manifest.mappingHash
    presentationHash = [string]$manifest.presentationHash
    mountMappingHash = [string]$manifest.typeMappingHashes.mount
    companionMappingHash = [string]$manifest.typeMappingHashes.companion
    toyMappingHash = [string]$manifest.typeMappingHashes.toy
    appearanceMappingHash = [string]$manifest.typeMappingHashes.appearance
    setMappingHash = [string]$manifest.typeMappingHashes.set
}
$contextPath = Join-Path $build 'round-two-build-context.json'
if (-not $WorldserverPath) {
    $context = [ordered]@{ schemaVersion = 1; buildStartedAtUtc = (Get-Date).ToUniversalTime().ToString('o'); values = $values }
    Write-RoundTwoJson $context $contextPath
}
$inc = @(
    '// Generated by tools/release/New-SoloCollectionsBuildInfo.ps1. Do not edit.',
    'namespace SoloCollectionsBuildInfo', '{'
)
foreach ($pair in $values.GetEnumerator()) {
    $escaped = ([string]$pair.Value).Replace('\\','\\\\').Replace('"','\\"')
    $inc += "inline constexpr char $($pair.Key)[] = `"$escaped`";"
}
$inc += '}'
$incPath = Join-Path $module 'src\generated\SoloCollectionsBuildInfo.inc'
[System.IO.File]::WriteAllText($incPath, ($inc -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "build_info_inc=$incPath"

if ($WorldserverPath) {
    $worldserver = Resolve-RoundTwoPath $WorldserverPath
    Assert-RoundTwoWithin -Path $worldserver -Root $build
    $pe = Get-RoundTwoPeInfo $worldserver
    if (-not $pe.IsX64) { throw "worldserver.exe is not x64" }
    $context = Read-RoundTwoJson $contextPath
    if ([DateTime]::Parse([string]$context.buildStartedAtUtc).ToUniversalTime() -gt (Get-Item -LiteralPath $worldserver).LastWriteTimeUtc) {
        throw "worldserver.exe predates recorded build start"
    }
    $cache = Join-Path $build 'CMakeCache.txt'
    $pdb = Join-Path (Split-Path -Parent $worldserver) 'worldserver.pdb'
    function Get-CMakeCacheValue([string]$Pattern) {
        if (-not (Test-Path -LiteralPath $cache)) { return 'UNAVAILABLE' }
        $match = Select-String -LiteralPath $cache -Pattern $Pattern | Select-Object -First 1
        if ($null -eq $match -or $match.Matches.Count -eq 0 -or $match.Matches[0].Groups.Count -lt 2) { return 'UNAVAILABLE' }
        return [string]$match.Matches[0].Groups[1].Value
    }
    $metadata = [ordered]@{
        schemaVersion = 1; configuration = $Configuration; buildStartedAtUtc = $context.buildStartedAtUtc
        buildFinishedAtUtc = (Get-Date).ToUniversalTime().ToString('o'); values = $values
        cmakeCacheSha256 = if (Test-Path -LiteralPath $cache) { Get-RoundTwoSha256 $cache } else { 'UNAVAILABLE' }
        generator = Get-CMakeCacheValue '^CMAKE_GENERATOR:INTERNAL=(.+)$'
        platform = Get-CMakeCacheValue '^CMAKE_GENERATOR_PLATFORM:INTERNAL=(.*)$'
        msvcVersion = Get-CMakeCacheValue '^CMAKE_CXX_COMPILER_VERSION:STRING=(.*)$'
        worldserverSha256 = Get-RoundTwoSha256 $worldserver
        worldserverMachine = $pe.Machine
        worldserverLastWriteUtc = (Get-Item -LiteralPath $worldserver).LastWriteTimeUtc.ToString('o')
        pdb = if (Test-Path -LiteralPath $pdb) { [ordered]@{ status='LOCAL_ONLY'; path=$pdb; sha256=Get-RoundTwoSha256 $pdb } } else { [ordered]@{ status='UNAVAILABLE'; path=''; sha256='' } }
    }
    $metadataPath = Join-Path $build 'module-build-metadata.json'
    Write-RoundTwoJson $metadata $metadataPath
    Write-Host "module_build_metadata=$metadataPath"
}
