-- Generated by tools/catalog/set_catalog.py. Do not edit.
SoloCollections.Data.Sets = {
    {
        id = 300000,
        itemSetId = 201,
        classToken = "MAGE",
        name = "奥术师套装",
        icon = "Interface\\Icons\\INV_Helmet_53",
        itemIds = {
            16798,
            16800,
            16801,
            16795,
            16796,
            16797,
            16802,
            16799
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206750
                        },
                        sourceItemIds = {
                            16798
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206757
                        },
                        sourceItemIds = {
                            16800
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206755
                        },
                        sourceItemIds = {
                            16801
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207095
                        },
                        sourceItemIds = {
                            16795
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206751
                        },
                        sourceItemIds = {
                            16796
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206756
                        },
                        sourceItemIds = {
                            16797
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206753
                        },
                        sourceItemIds = {
                            16802
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206754
                        },
                        sourceItemIds = {
                            16799
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300001,
        itemSetId = 203,
        classToken = "WARLOCK",
        name = "恶魔之心套装",
        icon = "Interface\\Icons\\INV_Shoulder_23",
        itemIds = {
            16809,
            16803,
            16805,
            16808,
            16810,
            16807,
            16806,
            16804
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207265
                        },
                        sourceItemIds = {
                            16809
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207267
                        },
                        sourceItemIds = {
                            16803
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207263
                        },
                        sourceItemIds = {
                            16805
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207273
                        },
                        sourceItemIds = {
                            16808
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207264
                        },
                        sourceItemIds = {
                            16810
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207266
                        },
                        sourceItemIds = {
                            16807
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207261
                        },
                        sourceItemIds = {
                            16806
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207262
                        },
                        sourceItemIds = {
                            16804
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300002,
        itemSetId = 204,
        classToken = "ROGUE",
        name = "夜幕杀手套装",
        icon = "Interface\\Icons\\INV_Helmet_41",
        itemIds = {
            16820,
            16824,
            16826,
            16821,
            16822,
            16823,
            16827,
            16825
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206958
                        },
                        sourceItemIds = {
                            16820
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206960
                        },
                        sourceItemIds = {
                            16824
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207087
                        },
                        sourceItemIds = {
                            16826
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207094
                        },
                        sourceItemIds = {
                            16821
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207054
                        },
                        sourceItemIds = {
                            16822
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207088
                        },
                        sourceItemIds = {
                            16823
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207053
                        },
                        sourceItemIds = {
                            16827
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206959
                        },
                        sourceItemIds = {
                            16825
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300003,
        itemSetId = 205,
        classToken = "DRUID",
        name = "塞纳里奥套装",
        icon = "Interface\\Icons\\INV_Helmet_09",
        itemIds = {
            16833,
            16829,
            16831,
            16834,
            16835,
            16836,
            16828,
            16830
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207192
                        },
                        sourceItemIds = {
                            16833
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207167
                        },
                        sourceItemIds = {
                            16829
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207169
                        },
                        sourceItemIds = {
                            16831
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207504
                        },
                        sourceItemIds = {
                            16834
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207170
                        },
                        sourceItemIds = {
                            16835
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207279
                        },
                        sourceItemIds = {
                            16836
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207166
                        },
                        sourceItemIds = {
                            16828
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207168
                        },
                        sourceItemIds = {
                            16830
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300004,
        itemSetId = 206,
        classToken = "HUNTER",
        name = "巨人追猎者套装",
        icon = "Interface\\Icons\\INV_Shoulder_10",
        itemIds = {
            16845,
            16849,
            16852,
            16846,
            16847,
            16848,
            16851,
            16850
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207282
                        },
                        sourceItemIds = {
                            16845
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207294
                        },
                        sourceItemIds = {
                            16849
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207283
                        },
                        sourceItemIds = {
                            16852
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207285
                        },
                        sourceItemIds = {
                            16846
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207286
                        },
                        sourceItemIds = {
                            16847
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207287
                        },
                        sourceItemIds = {
                            16848
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207280
                        },
                        sourceItemIds = {
                            16851
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207281
                        },
                        sourceItemIds = {
                            16850
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300005,
        itemSetId = 207,
        classToken = "SHAMAN",
        name = "大地之怒套装",
        icon = "Interface\\Icons\\INV_Shoulder_29",
        itemIds = {
            16841,
            16837,
            16839,
            16842,
            16843,
            16844,
            16838,
            16840
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207207
                        },
                        sourceItemIds = {
                            16841
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207205
                        },
                        sourceItemIds = {
                            16837
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207209
                        },
                        sourceItemIds = {
                            16839
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207210
                        },
                        sourceItemIds = {
                            16842
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207211
                        },
                        sourceItemIds = {
                            16843
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207208
                        },
                        sourceItemIds = {
                            16844
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207204
                        },
                        sourceItemIds = {
                            16838
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207206
                        },
                        sourceItemIds = {
                            16840
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300006,
        itemSetId = 208,
        classToken = "PALADIN",
        name = "秩序之源套装",
        icon = "Interface\\Icons\\INV_Helmet_05",
        itemIds = {
            16853,
            16859,
            16860,
            16854,
            16855,
            16856,
            16858,
            16857
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207089
                        },
                        sourceItemIds = {
                            16853
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207060
                        },
                        sourceItemIds = {
                            16859
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207091
                        },
                        sourceItemIds = {
                            16860
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207090
                        },
                        sourceItemIds = {
                            16854
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207058
                        },
                        sourceItemIds = {
                            16855
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207093
                        },
                        sourceItemIds = {
                            16856
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207059
                        },
                        sourceItemIds = {
                            16858
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            207092
                        },
                        sourceItemIds = {
                            16857
                        }
                    }
                }
            }
        },
        favorite = false
    },
    {
        id = 300007,
        itemSetId = 209,
        classToken = "WARRIOR",
        name = "力量套装",
        icon = "Interface\\Icons\\INV_Chest_Plate16",
        itemIds = {
            16865,
            16862,
            16863,
            16866,
            16867,
            16868,
            16864,
            16861
        },
        variants = {
            {
                variantKey = "tier1",
                colorKey = "default",
                difficultyKey = "raid",
                lifecycle = "active",
                requiredCount = 8,
                members = {
                    {
                        memberKey = "chest",
                        slotKey = "CHEST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206900
                        },
                        sourceItemIds = {
                            16865
                        }
                    },
                    {
                        memberKey = "feet",
                        slotKey = "FEET",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206904
                        },
                        sourceItemIds = {
                            16862
                        }
                    },
                    {
                        memberKey = "hands",
                        slotKey = "HANDS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206901
                        },
                        sourceItemIds = {
                            16863
                        }
                    },
                    {
                        memberKey = "head",
                        slotKey = "HEAD",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            210102
                        },
                        sourceItemIds = {
                            16866
                        }
                    },
                    {
                        memberKey = "legs",
                        slotKey = "LEGS",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206902
                        },
                        sourceItemIds = {
                            16867
                        }
                    },
                    {
                        memberKey = "shoulder",
                        slotKey = "SHOULDER",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206903
                        },
                        sourceItemIds = {
                            16868
                        }
                    },
                    {
                        memberKey = "waist",
                        slotKey = "WAIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206898
                        },
                        sourceItemIds = {
                            16864
                        }
                    },
                    {
                        memberKey = "wrist",
                        slotKey = "WRIST",
                        lifecycle = "active",
                        required = true,
                        appearanceIds = {
                            206899
                        },
                        sourceItemIds = {
                            16861
                        }
                    }
                }
            }
        },
        favorite = false
    }
}
